# Generated by Django 4.2.13 on 2024-07-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_citysearch_latitude_citysearch_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citysearch',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='citysearch',
            name='longitude',
        ),
        migrations.AddField(
            model_name='citysearch',
            name='city_id',
            field=models.IntegerField(default=0),
        ),
    ]
