# Generated by Django 4.2.13 on 2024-07-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_citysearch_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citysearch',
            name='city_id',
        ),
    ]
